# Generated by Django 3.2.19 on 2023-10-07 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_submit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='codesubmission',
            name='status',
            field=models.CharField(choices=[('todo', 'Todo'), ('solved', 'Solved'), ('attempted', 'Attempted')], default='todo', max_length=10),
        ),
    ]
