# Generated by Django 3.2.19 on 2023-10-11 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question_service', '0006_alter_question_difficulty'),
        ('code_submit', '0003_auto_20231008_0932'),
    ]

    operations = [
        migrations.AddField(
            model_name='codesubmission',
            name='framework_languages',
            field=models.ForeignKey(default=1,
                                    on_delete=django.db.models.deletion.CASCADE,
                                    to='question_service.frameworklanguage'),
            preserve_default=False,
        ),
    ]
