# Generated by Django 3.2.19 on 2023-09-30 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question_service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('input', models.TextField()),
                ('solution', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='question',
            name='status',
        ),
        migrations.RemoveField(
            model_name='question',
            name='testcase_id',
        ),
        migrations.DeleteModel(
            name='QuestionToSolution',
        ),
        migrations.AddField(
            model_name='testcase',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='question_service.question'),
        ),
    ]
