# Generated by Django 3.2.19 on 2023-09-30 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_service', '0002_auto_20230930_1147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='framework_id',
        ),
        migrations.RemoveField(
            model_name='question',
            name='language_id',
        ),
        migrations.AddField(
            model_name='framework',
            name='languages',
            field=models.ManyToManyField(related_name='frameworks', to='question_service.Language'),
        ),
        migrations.AddField(
            model_name='question',
            name='frameworks',
            field=models.ManyToManyField(related_name='questions', to='question_service.Framework'),
        ),
    ]
