# Generated by Django 3.2.19 on 2023-09-30 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question_service', '0003_auto_20230930_1444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='framework',
            name='languages',
        ),
        migrations.RemoveField(
            model_name='question',
            name='frameworks',
        ),
        migrations.CreateModel(
            name='FrameworkLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('framework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question_service.framework')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question_service.language')),
            ],
            options={
                'unique_together': {('framework', 'language')},
            },
        ),
        migrations.AddField(
            model_name='question',
            name='framework_languages',
            field=models.ManyToManyField(related_name='questions', to='question_service.FrameworkLanguage'),
        ),
    ]
