# Generated by Django 3.2.19 on 2024-01-02 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_service', '0006_alter_question_difficulty'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='question',
            name='tags',
        ),
        migrations.AddField(
            model_name='question',
            name='tags',
            field=models.ManyToManyField(blank=True, to='question_service.Tag'),
        ),
    ]
