# Generated by Django 5.0 on 2024-01-19 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("question_service", "0007_auto_20240102_0847"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="solution",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="question",
            name="difficulty",
            field=models.CharField(
                choices=[("Easy", "Easy"), ("Medium", "Medium"), ("Hard", "Hard")],
                default="Easy",
                max_length=6,
            ),
        ),
    ]
