# Generated by Django 5.0 on 2024-01-20 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("question_service", "0008_question_solution_alter_question_difficulty"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="skeleton_code",
            field=models.TextField(blank=True, null=True),
        ),
    ]
