# Generated by Django 5.0 on 2024-01-24 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("question_service", "0009_question_skeleton_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="frameworklanguage",
            name="skeleton_code",
            field=models.TextField(blank=True, null=True),
        ),
    ]
